Library-solider/codesquad-library

- server/src/main/java/kr/codesquad/library/controller/BookSearchController.java
- server/src/main/java/kr/codesquad/library/controller/OpenApiController.java
- server/src/main/java/kr/codesquad/library/domain/account/Account.java
- server/src/main/java/kr/codesquad/library/domain/account/LibraryRole.java
- server/src/main/java/kr/codesquad/library/domain/book/Book.java
- server/src/main/java/kr/codesquad/library/domain/book/response/BookDetailResponse.java
- server/src/main/java/kr/codesquad/library/domain/rental/Rental.java
- server/src/main/java/kr/codesquad/library/domain/rental/firstclass/Rentals.java
- server/src/main/java/kr/codesquad/library/global/api/ApiResult.java
- server/src/main/java/kr/codesquad/library/global/error/ErrorCode.java
- server/src/main/java/kr/codesquad/library/global/error/exception/domain/BookNotFoundException.java
- server/src/main/java/kr/codesquad/library/service/BookSearchService.java
- server/src/test/java/kr/codesquad/library/service/BookSearchServiceTest.java
> [Server] 도서 상세정보 기능 API

- server/src/main/java/kr/codesquad/library/controller/BookSearchController.java
- server/src/main/java/kr/codesquad/library/domain/rental/Rental.java
- server/src/main/java/kr/codesquad/library/domain/rental/firstclass/Rentals.java
- server/src/main/java/kr/codesquad/library/service/BookSearchService.java
- server/src/main/resources/application.yml
- server/src/test/java/kr/codesquad/library/controller/BookSearchControllerTest.java
- application.yml: 이전 설정인 show-sql: true 은 System.out 으로 출력.
log에서 출력하기 위해 org.hibernate.SQL: debug 재설정.
- BookSearchController
- getBookDetail(): raw 설정은 컴파일 에러 나기때문에 정확하게 설정함.
> [#39] refactor: 변수 설정, 서비스 트랜잭션 설정

- server/appspec.yml
- server/build.gradle
- server/buildspec.yml
- server/deploy.sh
- server/src/main/java/kr/codesquad/library/global/config/JasyptConfig.java
- server/src/main/resources/application.yml
- CodeBuild
- CodeDeploy
- CodePipeline
> [Server] AWS 환경 배포 추가

- server/src/main/java/kr/codesquad/library/domain/book/Book.java
- server/src/main/java/kr/codesquad/library/domain/book/response/BookDetailResponse.java
- server/src/main/java/kr/codesquad/library/global/config/JasyptConfig.java
- server/src/test/java/kr/codesquad/library/domain/book/BookRepositoryTest.java
- server/src/test/java/kr/codesquad/library/service/BookSearchServiceTest.java
- BookDetailResponse
- Book
: 렌탈 여부를 available로 변경
- JasyptConfig: 빈 이름 때문에 동작 불가.
> [#47] fix: 도서 컬럼 렌탈 여부 명 수정 및 Jasypt 빈 이름 변경

- server/src/main/java/kr/codesquad/library/domain/account/Account.java
- server/src/main/java/kr/codesquad/library/domain/book/response/BookDetailResponse.java
- server/src/main/java/kr/codesquad/library/domain/rental/Rental.java
- server/src/main/java/kr/codesquad/library/domain/rental/firstclass/Rentals.java
- server/src/main/java/kr/codesquad/library/global/api/ApiResult.java
- server/src/main/java/kr/codesquad/library/service/BookSearchService.java
- server/src/test/resources/application.yml
- Account: null 방지를 위한 LibraryRole의 컬럼 설정을 nullable false 로 변경 및 default value 'USER' 로 변경.
- BookDetailResponse: 조건문 변경.
- Rentals: 정적메소드 추가
- ApiResult: statusCode OK시 1로 반환. 변경 불가
> [#49] refactor: 3주차 리뷰를 통한 리팩토링

- server/src/main/java/kr/codesquad/library/controller/BookSearchController.java
- server/src/main/java/kr/codesquad/library/domain/book/response/BookSearchResponse.java
- server/src/main/java/kr/codesquad/library/global/error/ErrorCode.java
- server/src/main/java/kr/codesquad/library/global/error/GlobalRestExceptionHandler.java
- server/src/main/java/kr/codesquad/library/service/BookSearchService.java
- BookSearchResponse: 도서 검색 갯수 추가하기 위한 Dto생성.
- ErrorCode: 에러코드 추가. q 파라미터가 빠졌을경우에 대한 예외처리
- BookSearchService
- searchBooks(): BookSearchResponse를 반환하는 메서드. 기존의 메서드는 searchBooksList() 로 변경
> [#56] fix: 검색 파라미터 예외처리 및 검색 갯수 추가

- server/build.gradle
- server/src/main/java/kr/codesquad/library/domain/account/Account.java
- server/src/main/java/kr/codesquad/library/domain/account/AccountRepository.java
- server/src/main/java/kr/codesquad/library/domain/account/LibraryRole.java
- server/src/main/java/kr/codesquad/library/global/config/WebConfig.java
- server/src/main/java/kr/codesquad/library/global/config/oauth/SecurityConfig.java
- server/src/main/java/kr/codesquad/library/global/config/oauth/dto/OAuthAttributes.java
- server/src/main/java/kr/codesquad/library/global/config/oauth/dto/SessionAccount.java
- server/src/main/java/kr/codesquad/library/global/config/oauth/service/CustomOAuth2UserService.java
- server/src/main/java/kr/codesquad/library/global/config/oauth/service/OAuth2Service.java
- server/src/test/java/kr/codesquad/library/controller/BookSearchControllerTest.java
- server/src/test/java/kr/codesquad/library/controller/annotation/WithAdmin.java
- server/src/test/java/kr/codesquad/library/controller/annotation/WithGuest.java
- server/src/test/java/kr/codesquad/library/controller/annotation/WithUser.java
- server/src/test/resources/application.yml
- OAuth 로그인 하면 자동으로 GUEST로 가입
- OAuth 로그인 성공하면 session으로 저장.
> [Server] 회원가입 기능 추가

- server/build.gradle
- server/src/main/java/kr/codesquad/library/domain/account/Account.java
- server/src/main/java/kr/codesquad/library/domain/account/AccountRepository.java
- server/src/main/java/kr/codesquad/library/domain/account/LibraryRole.java
- server/src/main/java/kr/codesquad/library/global/config/WebConfig.java
- server/src/main/java/kr/codesquad/library/global/config/oauth/SecurityConfig.java
- server/src/main/java/kr/codesquad/library/global/config/oauth/dto/OAuthAttributes.java
- server/src/main/java/kr/codesquad/library/global/config/oauth/dto/SessionAccount.java
- server/src/main/java/kr/codesquad/library/global/config/oauth/service/CustomOAuth2UserService.java
- server/src/main/java/kr/codesquad/library/global/config/oauth/service/OAuth2Service.java
- server/src/main/resources/application.yml
- server/src/test/java/kr/codesquad/library/controller/BookSearchControllerTest.java
- server/src/test/java/kr/codesquad/library/controller/annotation/WithAdmin.java
- server/src/test/java/kr/codesquad/library/controller/annotation/WithGuest.java
- server/src/test/java/kr/codesquad/library/controller/annotation/WithUser.java
- server/src/test/resources/application.yml
- LocalDate 타입이 배열로 나와서 git reset --hard 로 돌렸습니다. LocalDate 타입이 정상적으로 나오는 브랜치를 이용하여 PR -> merge 합니다.
> [Server] git reset --hard 로 인해 jackson 되돌린 상태를 PR -> merge

- server/build.gradle
- server/src/main/java/kr/codesquad/library/controller/BookSearchController.java
- server/src/main/java/kr/codesquad/library/domain/account/Account.java
- server/src/main/java/kr/codesquad/library/domain/account/AccountRepository.java
- server/src/main/java/kr/codesquad/library/domain/account/LibraryRole.java
- server/src/main/java/kr/codesquad/library/domain/book/BookRepository.java
- server/src/main/java/kr/codesquad/library/domain/book/response/BookSearchResponse.java
- server/src/main/java/kr/codesquad/library/global/config/WebConfig.java
- server/src/main/java/kr/codesquad/library/global/config/oauth/SecurityConfig.java
- server/src/main/java/kr/codesquad/library/global/config/oauth/dto/OAuthAttributes.java
- server/src/main/java/kr/codesquad/library/global/config/oauth/dto/SessionAccount.java
- server/src/main/java/kr/codesquad/library/global/config/oauth/service/CustomOAuth2UserService.java
- server/src/main/java/kr/codesquad/library/global/config/oauth/service/OAuth2Service.java
- server/src/main/java/kr/codesquad/library/global/error/ErrorCode.java
- server/src/main/java/kr/codesquad/library/global/error/GlobalRestExceptionHandler.java
- server/src/main/java/kr/codesquad/library/service/BookSearchService.java
- server/src/main/resources/application.yml
- server/src/test/java/kr/codesquad/library/controller/BookSearchControllerTest.java
- server/src/test/java/kr/codesquad/library/controller/annotation/WithAdmin.java
- server/src/test/java/kr/codesquad/library/controller/annotation/WithGuest.java
- server/src/test/java/kr/codesquad/library/controller/annotation/WithUser.java
- server/src/test/java/kr/codesquad/library/domain/book/BookRepositoryTest.java
- server/src/test/resources/application.yml
- 도서 제목 검색 기능 API
- 로그인 기능 OAuth2 세션으로 구현 (서버가 한대이므로 JWT를 할 필요가 없다고 생각하여 세션으로 사용)
- 로그인해서 "/"로 돌아가도록 설정
- Security OAuth2 로그인을 처음 사용해서 작동방식에 대해서 공부중입니다. 많이 어렵네요.
- 지난번에 지적하셨던데로 브랜치를 따로 따서 리뷰올렸습니다. 중간에 코드가 바뀔일은 없습니다.
> [Server] 3번째 코드 리뷰입니다.

- deploy.sh
- src/main/java/kr/codesquad/library/global/config/SecurityConfig.java
- SecurityConfig: 로그인 성공하면 localhost:3000으로 이동
> [#52] fix: Redirect url 변경

- src/main/java/kr/codesquad/library/domain/book/BookRepository.java
- src/main/java/kr/codesquad/library/domain/book/response/BookDetailResponse.java
- src/main/java/kr/codesquad/library/domain/book/response/BookResponse.java
- src/main/java/kr/codesquad/library/domain/book/response/BookSearchResponse.java
- src/main/java/kr/codesquad/library/domain/book/response/BooksByCategoryResponse.java
- src/main/java/kr/codesquad/library/global/config/oauth/security/OAuth2SuccessHandler.java
- src/main/java/kr/codesquad/library/service/BookSearchService.java
- src/main/resources/application.yml
- src/test/java/kr/codesquad/library/domain/book/BookRepositoryTest.java
- src/test/java/kr/codesquad/library/service/BookSearchServiceTest.java
- src/test/resources/application.yml
- 로컬: localhost:3000
- 배포: http://librarycodesquad.com
- 검색 띄어쓰기에 따라 한글 검색이 달라지는 버그를 수정.
> [Server] OAuth2 리다이렉트 주소 변경 및  검색 버그 수정

- src/main/java/kr/codesquad/library/controller/AccountController.java
- src/main/java/kr/codesquad/library/domain/account/response/AccountProfileResponse.java
- src/main/java/kr/codesquad/library/service/AccountService.java
- src/test/java/kr/codesquad/library/service/AccountServiceTest.java
- AccountController: users/ 매핑하여 리팩토링.
> [#91] feat: 로그인용 프로필 아이디, 아바타이미지 API 기능 추가

- src/main/java/kr/codesquad/library/domain/rental/RentalRepository.java
- src/main/java/kr/codesquad/library/service/BookService.java
- RentalRepository
- findByBookAndAccountAndIsReturnedFalse(): 반납하지 않은 대여를 가져옴.
> [#93] fix: 대여를 한 도서를 다시 빌리고 반납할 때 버그 수정

- src/main/java/kr/codesquad/library/controller/AccountController.java
- src/main/java/kr/codesquad/library/controller/BookController.java
- src/main/java/kr/codesquad/library/domain/account/Account.java
- src/main/java/kr/codesquad/library/domain/account/response/AccountMyPageResponse.java
- src/main/java/kr/codesquad/library/domain/book/Book.java
- src/main/java/kr/codesquad/library/domain/book/BookRepository.java
- src/main/java/kr/codesquad/library/domain/book/response/BookSearchResponse.java
- src/main/java/kr/codesquad/library/domain/rental/Rental.java
- src/main/java/kr/codesquad/library/domain/rental/firstclass/Rentals.java
- src/main/java/kr/codesquad/library/global/config/oauth/security/CustomOAuth2UserService.java
- src/main/java/kr/codesquad/library/service/BookService.java
- src/test/java/kr/codesquad/library/domain/book/BookRepositoryTest.java
- src/test/java/kr/codesquad/library/service/AccountServiceTest.java
- src/test/java/kr/codesquad/library/service/BookServiceTest.java
- AccountController: swagger를 위한 설정 추가.
- BookController
- primitive -> Wrapper 변경.
- AccountMyPageResponse: 복수형으로 변경.
- Account: 애노테이션 순서 재정렬.
- BookSearchResponse: Pageable 에서 제공하는 getTotalElement()가 Long으로 return하여 변경.
- Book
- rentalBook(), returnBook(): 혼합될 가능성이 있어 메서드 분리함.
- BookRepository
- findByTitleIgnoreCaseContainingOrAuthorIgnoreCaseContaining
: List로 따로 따로 가져와서 자바소스에서 페이지네이션처리하지 않기 위해 DB요청할 때부터 페이지네이션 요청하도록 변경. Title과 Author를 같이 검색하기위해 Or문 사용.
- Rentals: 메서드명 확실히 하기.(draw하는 대상 구체적으로 표시)
- Rental: 애노테이션 순서 재정렬. 반납일수에 대한 정보는 주석으로 따로 표시함.
- BookService
- MAX_RENTAL_SIZE: 최대 도서 대여 숫자를 최상단에서 표시.
- findByCategoryId(): CategoryId로 탐색한다고 명확히 함.
- searchBooks(): 두개의 메서드에서 하나의 메서드에서 처리하도록 변경. bookCount에서 getTotalElemenst()를 통해 검색결과 데이터 숫자표시함.
> [#98] refactor: 코드리뷰 배경으로 리팩토링 실행

- src/main/java/kr/codesquad/library/controller/AccountController.java
- src/main/java/kr/codesquad/library/controller/OpenApiController.java
- src/main/java/kr/codesquad/library/global/config/SecurityConfig.java
- src/main/java/kr/codesquad/library/global/config/oauth/security/CustomAccessDeniedHandler.java
- src/main/java/kr/codesquad/library/global/config/oauth/security/CustomAuthenticationEntryPoint.java
- src/main/java/kr/codesquad/library/global/error/ErrorCode.java
- src/main/java/kr/codesquad/library/global/error/ErrorResponse.java
- src/main/java/kr/codesquad/library/global/error/GlobalRestExceptionHandler.java
401 처리될 경우 자동 모달창이 생겨 400 Bad Request로 변경.
> [Server] 401, 403 에러처리 수정

- src/main/java/kr/codesquad/library/domain/account/response/AccountMyPageResponse.java
- src/main/java/kr/codesquad/library/domain/account/response/AccountProfileResponse.java
- src/main/java/kr/codesquad/library/domain/book/response/BookDetailResponse.java
- src/main/java/kr/codesquad/library/domain/book/response/BookResponse.java
- src/main/java/kr/codesquad/library/domain/book/response/BookSearchResponse.java
- src/main/java/kr/codesquad/library/domain/book/response/BooksByCategoryResponse.java
- src/main/java/kr/codesquad/library/domain/rental/Rental.java
- src/main/java/kr/codesquad/library/domain/rental/firstclass/Rentals.java
- src/main/java/kr/codesquad/library/service/AccountService.java
- src/main/java/kr/codesquad/library/service/BookService.java
- src/test/java/kr/codesquad/library/service/BookServiceTest.java
- of: 매개변수가 2개이상일 때 사용.
- from: 매개변수가 1개일 때 사용.
> [#115] refactor: Dto of, from 메서드 역할을 잘못이해하여 재수정

- src/main/java/kr/codesquad/library/admin/controller/AccountAdminController.java
- src/main/java/kr/codesquad/library/admin/domain/account/AccountAdminRepository.java
- src/main/java/kr/codesquad/library/admin/service/AccountAdminService.java
- src/main/java/kr/codesquad/library/domain/account/Account.java
- src/main/java/kr/codesquad/library/global/config/SecurityConfig.java
- src/main/resources/static/css/main.css
- src/main/resources/static/js/index.js
- src/main/resources/templates/index.html
- src/test/java/kr/codesquad/library/admin/service/AccountAdminServiceTest.java
- ROLE이 GUEST인 회원 전체 목록을 조회하는 기능
- ROLE이 GUEST인 회원을 USER로 변경(권한 승인) 기능
- Ajax Request 및 테이블 변경 내용 실시간으로 뷰에 반영
> [Admin] 회원 권한 승인 API 구현

- src/main/java/kr/codesquad/library/domain/rental/response/RentalBookResponse.java
- src/main/java/kr/codesquad/library/global/error/ErrorCode.java
- src/main/java/kr/codesquad/library/global/error/GlobalRestExceptionHandler.java
- RentalBookResponse: 책 id, 책 이미지 URL 필드 값 추가.
- 검색 시 q param이 없을 경우 status code 코드를 400이 아닌 404로 변경. 400일 경우 로그아웃으로 프론트로 처리하기 때문에 404 Not Found로 변경함.
> [#125] feat: 도서 대여 목록 필드값 추가 및 404 코드 변경

- src/main/java/kr/codesquad/library/domain/rental/response/RentalBookResponse.java
- src/test/java/kr/codesquad/library/service/AccountServiceTest.java
> [#128] feat: 도서 대여 목록 저자 추가 및 대여일 삭제

- src/main/java/kr/codesquad/library/admin/controller/AccountAdminController.java
- src/main/java/kr/codesquad/library/admin/controller/AuthAdminController.java
- src/main/java/kr/codesquad/library/admin/domain/account/AccountAdminRepository.java
- src/main/java/kr/codesquad/library/admin/domain/account/AccountSummaryResponse.java
- src/main/java/kr/codesquad/library/admin/service/AccountAdminService.java
- src/main/java/kr/codesquad/library/global/config/SecurityConfig.java
- src/main/resources/static/js/ajaxRequest.js
- src/main/resources/templates/account/all-accounts.html
- src/main/resources/templates/account/guest-accounts.html
- src/test/java/kr/codesquad/library/admin/service/AccountAdminServiceTest.java
- 회원 데이터가 너무 적어서 뷰 테스트가 매끄럽지 못합니다. 따라서 테스트 효율성을 위해 데이터가 충분히 확보 되어 있는 도서 목록 조회 API 기능 구현 시 페이징 기능을 함께 추가 할 예정 입니다.
> [Admin] 회원 목록 조회 기능 구현

- src/main/java/kr/codesquad/library/admin/controller/AccountAdminController.java
- src/main/java/kr/codesquad/library/admin/domain/account/AccountDetailsResponse.java
- src/main/java/kr/codesquad/library/admin/service/AccountAdminService.java
- src/main/resources/static/css/details-account.css
- src/main/resources/static/css/footer.css
- src/main/resources/static/css/main.css
- src/main/resources/static/css/styles.css
- src/main/resources/static/js/accountDataTableHandler.js
- src/main/resources/static/js/accountDataTableSelector.js
- src/main/resources/static/js/ajaxRequest.js
- src/main/resources/templates/account/all-accounts.html
- src/main/resources/templates/account/details-account.html
- src/main/resources/templates/account/guest-accounts.html
- src/test/java/kr/codesquad/library/admin/service/AccountAdminServiceTest.java
<br>
<strong>대여중인 도서 항목은 삭제 예정</strong>
> [Admin] 회원 상세 정보 조회 기능 구현

- src/main/java/kr/codesquad/library/admin/common/PagingProperties.java
- src/main/java/kr/codesquad/library/admin/controller/BookAdminController.java
- src/main/java/kr/codesquad/library/admin/domain/book/BookDetailResponse.java
- src/main/java/kr/codesquad/library/admin/service/BookAdminService.java
- src/main/resources/static/css/books-detail.css
- src/main/resources/static/css/main.css
- src/main/resources/static/css/styles.css
- src/main/resources/static/js/bookDataTableHandler.js
- src/main/resources/templates/book/books-all.html
- src/main/resources/templates/book/books-detail.html
- src/test/java/kr/codesquad/library/admin/service/BookAdminServiceTest.java
- 도서 상세 정보 조회
- 관련 View , CSS, JS 적용
- 도서 테이블 목록에서 상세 정보로 이동할 수 있도록 연동
> [Admin] 도서 상세 정보 조회 기능 구현

- src/main/java/kr/codesquad/library/admin/controller/BookAdminController.java
- src/main/java/kr/codesquad/library/admin/controller/CategoryAdminController.java
- src/main/java/kr/codesquad/library/admin/domain/book/BookAdminRepository.java
- src/main/java/kr/codesquad/library/admin/domain/book/request/BookMoveRequest.java
- src/main/java/kr/codesquad/library/admin/service/BookAdminService.java
- src/main/java/kr/codesquad/library/admin/service/CategoryAdminService.java
- src/main/java/kr/codesquad/library/domain/book/Book.java
- src/main/java/kr/codesquad/library/domain/category/Category.java
- src/main/java/kr/codesquad/library/global/error/ExceptionView.java
- src/main/java/kr/codesquad/library/global/error/GlobalRestExceptionHandler.java
- src/main/java/kr/codesquad/library/global/error/exception/AdminException.java
- src/main/java/kr/codesquad/library/global/error/exception/admin/DeleteEntityDeniedException.java
- src/main/resources/static/css/categories-books.css
- src/main/resources/static/css/delete-denied.css
- src/main/resources/static/css/grid-items.css
- src/main/resources/static/css/styles.css
- src/main/resources/static/js/ajaxBookRequest.js
- src/main/resources/static/js/ajaxRequest.js
- src/main/resources/static/js/bookDataTableHandler.js
- src/main/resources/static/js/bookMoveRequest.js
- src/main/resources/static/js/deleteButtonHandler.js
- src/main/resources/templates/category/categories-all.html
- src/main/resources/templates/category/categories-books.html
- src/main/resources/templates/exception/delete-denied.html
- src/test/java/kr/codesquad/library/admin/service/BookAdminServiceTest.java
- src/test/java/kr/codesquad/library/admin/service/CategoryAdminServiceTest.java
- 새로운 카테고리 등록 기능
- 카테고리의 title 수정 기능
- 특정 카테고리 삭제 기능
- 해당 카테고리에 도서가 있을 경우 삭제가 불가능하다. 
- 비즈니스 로직상 도서는 반드시 하나의 카테고리, 하나의 책장에 위치해야 하므로 도메인간 무결성을 지키기 위해 삭제를 허용하지 않는다.
- 삭제가 필요한 경우 도서를 다른 그룹으로 이동 시킬 수 있도록 카테고리 / 위치 이동 기능 구현 (카테고리별 도서 목록에서 가능)
> [Admin] 카테고리 등록 / 수정 / 삭제 기능 완료

- src/main/java/kr/codesquad/library/admin/service/BookcaseAdminService.java
- src/main/java/kr/codesquad/library/admin/service/CategoryAdminService.java
BookcaseAdminService,
CategoryAdminService
> [#148] fix: 카테고리별 도서, 위치별 도서 조회 페이지 요청 validation 코드 추가

- src/main/resources/static/css/books-detail.css
- src/main/resources/static/js/accountCheckBoxDataTableHandler.js
- src/main/resources/templates/account/guest-accounts.html
권한 승인 목록에서 회원 상세정보 조회가 되지 않던 오류 수정
> [Hoxfix] Admin 오류 수정

- src/main/java/kr/codesquad/library/global/error/GlobalRestExceptionHandler.java
GlobalRestExceptionHandler
- FORBIDDEN -> BAD_REQUEST
> [Admin] Admin 예외 반환 Status code 변경

- src/main/java/kr/codesquad/library/admin/controller/BookcaseAdminController.java
- src/main/java/kr/codesquad/library/admin/controller/CategoryAdminController.java
컨트롤러 계층에서 page - 1로 넘겨주던 로직이 validation 코드에서도 중복. 이에 따라 오류가 발생하여 수정
BookcaseAdminController,
CategoryAdminController
> [HotFix] 카테고리, 도서 위치 페이지네이션 오류 수정

- src/main/resources/static/css/books-createform.css
> [#148] fix: 도서 등록 / 수정 폼에서 URL 타입 input 요소에 스타일 적용 안되던 문제 수정

- src/main/java/com/librarycodesquad/prod/controller/AccountController.java
- src/main/java/com/librarycodesquad/prod/global/config/SecurityConfig.java
- SecurityConfig
- logout(): 로그인 URL 설정 및 성공 URL
> [#172] feat: 로그아웃 기능 추가

- src/main/java/com/librarycodesquad/admin/service/BookAdminService.java
> [#174] fix: 도서 대여 목록 반납일자 빠른순으로 정렬.

- src/main/java/com/librarycodesquad/admin/domain/book/response/BookDetailResponse.java
- src/main/java/com/librarycodesquad/prod/domain/rental/Rental.java
- src/main/resources/static/css/details-account.css
- src/main/resources/templates/account/details-account.html
- src/main/resources/templates/book/books-detail.html
- Rental에서 Account의 필드 값들을 직접 꺼내는 것이 아니라, Account 객체를 먼저 가져온 뒤 해당 객체에서 직접 필드를 꺼내도록 하는 것이 맞지 않을까?
- Rental에서 Account의 필드인 name, id를 직접 가져오는 것에 대해 논의해본 뒤 필요하다면 수정 할 예정
> 대여중인 도서와 대여중인 회원 정보 조회 기능 구현 완료

- build.gradle
- docker-compose.yml
- src/main/resources/application.yml
> [#178] refactor : 스프링, 자바 버전 업

- src/main/resources/application.yml
> [#181] refactor : yaml 설정 변경

- build.gradle
- src/main/resources/application.yml
> [#181] refactor : yaml profile deprecated 설정 변경

- src/main/resources/application.yml
> [#181] refactor : MySQL Url 환경변수 변경 및 주소 문자열 설정

- src/main/resources/application.yml
> [#181] refactor : MySQL 환경변수 이름 변경
